### ISSUE TITLE
tslint 已废弃

### ISSUE THREAD

**Issue by zhuiyue132** [luoxue-victor/workflow#10]
rt

**Comment by luoxue-victor** [comment]
确实已经废弃了 可以看 TSLINT --> ESLINT

https://github.com/palantir/tslint/issues/4534

**Comment by zhuiyue132** [comment]
我的意思是你的课时12 可以不用做了:grin:

**Comment by luoxue-victor** [comment]
eslint 只能检查语法错误，并不能检查类型错误
