### ISSUE TITLE
http 代理，配合mock

### ISSUE THREAD

**Issue by luoxue-victor** [luoxue-victor/workflow#12]

**Comment by chenweihuan** [comment]
```js
module.exports = {
  ...
  devServer: {
    open: false, // 是否打开浏览器
    host: "0.0.0.0", // 可让你的应用跑在不同的机器上，使用localhost或IP访问
    proxy: {
      // 仅代理/api和/api2开头的接口
      "/(api|api2)": {
        target:
          "http://...:4000" // 目标代理接口地址
      }
    }
  }
};
```
这样？我最近也在总结webpack的配置，不过是针对vue-cli。[vue-cli3-config-reference](https://github.com/chenweihuan/vue-cli3-config-reference)

**Comment by luoxue-victor** [comment]
> ```js
> ```js
> module.exports = {
>   ...
>   devServer: {
>     open: false, // 是否打开浏览器
>     host: "0.0.0.0", // 可让你的应用跑在不同的机器上，使用localhost或IP访问
>     proxy: {
>       // 仅代理/api和/api2开头的接口
>       "/(api|api2)": {
>         target:
>           "http://...:4000" // 目标代理接口地址
>       }
>     }
>   }
> };
> ```
> 
> 
> 这样？我最近也在总结webpack的配置，不过是针对vue-cli。vue-cli3-config-reference
> ```

这块还没太想好怎么弄，没有定下最终方案，我也是参考的vue-cli3，有兴趣一起来搞啊

**Comment by Maruda1986** [comment]
> ```js
> module.exports = {
>   ...
>   devServer: {
>     open: false, // 是否打开浏览器
>     host: "0.0.0.0", // 可让你的应用跑在不同的机器上，使用localhost或IP访问
>     proxy: {
>       // 仅代理/api和/api2开头的接口
>       "/(api|api2)": {
>         target:
>           "http://...:4000" // 目标代理接口地址
>       }
>     }
>   }
> };
> ```
> 
> 这样？我最近也在总结webpack的配置，不过是针对vue-cli。[vue-cli3-config-reference](https://github.com/chenweihuan/vue-cli3-config-reference)

vff
