### ISSUE TITLE
第二课时，base.js中引入lib做什么的

### ISSUE THREAD

**Issue by conan51551** [luoxue-victor/workflow#36]
看不懂读取config的文件路径，然后做了什么，照着课时做又报错，lib中的代码也是clone下来找到的，但是还是报错

**Comment by luoxue-victor** [comment]
读取了文件路径之后，引入文件，将配置导入，你可以切换到课时2 分支上进行操作试一下

**Comment by conan51551** [comment]
切换分支是好了。
