### ISSUE TITLE
[request]: better branch naming

### ISSUE THREAD

**Issue by seognil** [luoxue-victor/workflow#56]
现在 分支有的叫`课时`，有的叫`课题`，望统一
并且中文名称不太利于命令行中操作

是否可以改成 `lesson-1` 这样的形式~

以及在 master 的 readme 中补充说明：`课题需要切换对应分支进行实践`
现在没有说明容易造成困惑… #36

**Comment by luoxue-victor** [comment]
感谢🙏，后面会统一分支名
