### ISSUE TITLE
[DllPlugin] Uncaught ReferenceError: dll is not defined

### ISSUE THREAD

**Issue by juntingl** [luoxue-victor/workflow#58]
通过 DllPlugin 拆分包后，缺少将生成的 **dll** 文件提前插入到 **html** 中。

**Comment by yuyeqianxun** [comment]
是不是从第6课时开始？我也发现了，1.6k星星的项目，很多人点了星星就跑，根本不看的，还有public下的html标签都是错的，也没人发现。开源是挺好挺辛苦的，可惜没人看，只收获了点星星。另外我查了些资料，dll.js是需要引入的，up应该是想着手动引入，add-asset-html-webpack-plugin这个插件也能办得到

**Comment by yuyeqianxun** [comment]
> 是不是从第6课时开始？我也发现了，1.6k星星的项目，很多人点了星星就跑，根本不看的，还有public下的html标签都是错的，也没人发现。开源是挺好挺辛苦的，可惜没人看，只收获了点星星。另外我查了些资料，dll.js是需要引入的，up应该是想着手动引入，add-asset-html-webpack-plugin这个插件也能办得到

贴一下代码吧，
```
/**
*config/ZaddAssetHtmlPlugin.js文件
*(由于插件有执行顺序的问题，请将该文件配置在最后，所以用Z开头命名)
*/
const AddAssetHtmlPlugin = require('add-asset-html-webpack-plugin');

module.exports = (config, resolve) => {
  return () => {
    config.plugin('AddAssetHtmlPlugin')
        .use(AddAssetHtmlPlugin, [{
            filepath: require.resolve('../dll/dll.js')
        }])
    }
}
```

**Comment by luoxue-victor** [comment]
感谢反馈，当时写的时候没有想到有这么多人看，我写的比较简易，后续我会补充一下
